spring:
  application:
    name: reservation
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reservation?serverTimezone=UTC&characterEncoding=UTF-8
    username: hj
    password: zerobase

  jpa:
   hibernate:
     ddl-auto: create-drop
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MariaDBDialect